### ISSUE TITLE
Highlighted code doesn't have syntax colors.

### ISSUE THREAD

**Issue by viktomas** [gilgigilgil/anderson.vim#3]
Hi, is there any way how to make syntax colors visible on the highlighted (current)  line?

**Comment by tlhr** [comment]
I fixed this by moving some colors around and adding another shade of gray. Visual selections should behave properly now as well.

**Comment by viktomas** [comment]
Hi @gilgigilgil, thanks for the commit. I still can't see highlighted syntax though, Is there any way how I can help you fix this?
<img width="963" alt="screen shot 2015-10-31 at 7 41 59 am" src="https://cloud.githubusercontent.com/assets/1079718/10857618/40bd6146-7fa3-11e5-8d15-11303b99cd7a.png">

(version of your repo I'm using is the current head on master)

**Comment by tlhr** [comment]
@viktomas, what terminal emulator, os, and vim version are you using?

**Comment by viktomas** [comment]
OS: OS X 10.11.1 (El Capitan)
Terminal emulator: iTerm2 2.1.4
vim: neovim (roughly 2 weeks old build) (Commit: a3f048ee06dea15490d7b874d295c3fc850cdc51)

**Comment by tlhr** [comment]
Hi @viktomas, sorry for the late reply. I can't reproduce this. Have you tried completely removing the colorscheme and reinstalling it? This sounds like a syncing issue with your vim plugin manager.
